### ISSUE TITLE
Valves and Pumps are not exported correctly to a Shape file

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#25] opened 2016-12-01 18:52 UTC
When exporting an EPANET network to a Shape file, valves and pumps are not exported correctly. Instead of valves and pumps the result is another shp file of the pipes.
Here is the pumps layer in QGIS:

![screenshot 265](https://cloud.githubusercontent.com/assets/1942312/20807535/fe50504a-b807-11e6-82af-08ae121e5b00.png)

**Comment by MarkGrayRESPEC** [comment] 2016-12-01 21:39
Thank you for this report, I have now fixed the issue in the code so this will be fixed in the upcoming release. This was caused by a missing check for whether it was attempting to save all items in one file or in separate files. When saving as GeoJSON, we save all items in one file, when saving to shp, they are separate.

**Closed by MarkGrayRESPEC** 2016-12-01 21:39 UTC
