### ISSUE TITLE
Adding Calibration files causes program to crash

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#404] opened 2020-02-26 22:22 UTC
![image](https://user-images.githubusercontent.com/26123284/75393628-7ea41580-58bc-11ea-8345-d2990689d864.png)

![image](https://user-images.githubusercontent.com/26123284/75393654-88c61400-58bc-11ea-9e4a-2c82f2c81945.png)

**Comment by barrc** [comment] 2020-02-27 00:06
I can reproduce -- it crashes when I click 'OK' after selecting a file.  I think it's crashing because `self.file_dict` is not defined at line 93 of frmCalibrationData.  I haven't used calibration data much, so I'm not sure why the calibration file data is being stored in defaults.

**Comment by barrc** [comment] 2020-03-20 23:57
In the Delphi GUI the calibration data is stored in the project-specific .ini file:

```
[Calibration]
File1=C:\Users\cbarr02\Desktop\climate_data_philly.dat
File2=
File3=
File4=
File5=
File6=
File7=
File8=
File9=
File10=
File11=
File12=
```

So I think the next step is looking at the project-specific .ini file for the new GUI.

**Comment by michelleannesimon** [comment] 2020-03-30 14:21
I have had the same experience:
![image](https://user-images.githubusercontent.com/26123284/77923287-3b004b00-7270-11ea-8323-24779894324d.png)

**Comment by PaulDudaRESPEC** [comment] 2020-05-14 02:10
I think I fixed this issue with a commit moments ago, but I don't have very good calibration data to test with, so maybe @michelleannesimon you could test and verify this fixes the problem.

**Comment by dickinsonre** [comment] 2020-05-14 02:13
So you want to have all types of calibration files?  It would be best to test them all = I can supply them today or on Thursday.  
![image](https://user-images.githubusercontent.com/5599939/81884844-f81bdd80-9566-11ea-85a4-cbc595354477.png)

**Comment by dickinsonre** [comment] 2020-05-14 11:03
Here is the simple model and the calibration files that go with the simple model.
[Extran1_Egg.zip](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/4627812/Extran1_Egg.zip)

**Comment by PaulDudaRESPEC** [comment] 2020-05-14 12:13
Thanks, @dickinsonre .  I'll test with these, and I'd also like to test with the same files that @michelleannesimon is attempting to use.

**Comment by PaulDudaRESPEC** [comment] 2020-05-19 00:29
as per discussion with @michelleannesimon on 5/15/2020, this bug is now fixed

**Closed by PaulDudaRESPEC** 2020-05-19 00:29 UTC
Labels: bug
