### ISSUE TITLE
EPANET_MTP4r2_Create new file button at standard menu crashes

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#230] opened 2018-01-27 21:37 UTC
Create new file using the button on standard menu crashes the program. 

Way to reproduce:
Open a file then close it and then create a new file

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by dickinsonre** [comment] 2018-01-27 22:26
This command does seem to work in the SWMM5 new GUI MTP4r2a and in the EPANET new GUI using Windows 10

**Comment by dickinsonre** [comment] 2018-01-27 22:28
![2018-01-27_1722](https://user-images.githubusercontent.com/5599939/35476950-693380b4-0387-11e8-89e0-28cd8c32a331.png)

**Comment by ehsanMa86** [comment] 2018-01-27 22:50
Double Checked. Windows 10 and still crashes:
![untitled](https://user-images.githubusercontent.com/33101556/35477120-28c2260c-0382-11e8-9f2a-901194d4e361.png)

**Comment by barrc** [comment] 2018-01-30 19:49
I can reproduce this for SWMM on Windows 10 Enterprise.  I also get a crash by opening the UI, closing the initial (blank) canvas, then doing file -> new or clicking the 'start a new project' button on the standard toolbar.

**Comment by TongZhai** [comment] 2018-08-24 14:56
@ehsanMa86 @barrc The essence of the issue is that the software relies on the existence of the map display in the UI, hence, when it is closed/destroyed, some functions will stop working. So, the solution is to prevent users from closing it, which is the sensible thing to do. However, after extensive research and trials, it appears that PyQt (4 or 5) doesn't expose enough API event handling functions to allow effective control of its closing. C++ API does. So, at the moment, I think we should add some text in the documentation to warn user against closing the map display. If they did, they have to close the software and restart it to get the map display back. We will keep this issue open, in case in the future there will be additional PyQt APIs that we can use to control it.

**Comment by PaulDudaRESPEC** [comment] 2019-05-14 20:14
It looks like the API now has a method for removing the 'Close' button from the map panel -- I'll check in this change momentarily...

**Closed** 2019-05-14 20:25 UTC
Labels: EPANET, bug
